name: Tests Python

on:
  push:
    branches: ["**"]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      # 1) Récupération du code
      - name: Checkout
        uses: actions/checkout@v4

      # 2) Installation de Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11.0"

      # 3) Mettre en cache le dossier pip (accélère les exécutions)
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # 4) Installer les dépendances
      - name: Install dependencies
        run: pip install -e .

      # 5) Lancer les tests
      - name: Run pytest
        run: pytest